### ISSUE TITLE
Feature request: Adding Liquid tag support to this package

### ISSUE THREAD

**Issue by fusion809** [zhuochun/md-writer#128]
Hi,

I frequently use this plugin when writing posts in my Jekyll site ([The Hornery](https://fusion809.github.io) &mdash; [source](https://github.com/fusion809/fusion809.github.io)) and I think it would make things alot easier if this package had support for Liquid tags. So that when one types `{%` this plugin automatically closes the tag with `%}`. Also keyboard shortcuts for inserting `{% include %}`, `{% include_relative %}`, `{% capture %}`, `{% endcapture %}`, `{% if %}`, `{% elsif %}`, `{% endif %}` would be helpful.

Thanks for your time,
Brenton

**Comment by zhuochun** [comment]
Auto closing tags seems to be a potential feature to support.

`{% include %}` etc probably look like using snippets are better and easier.

**Comment by puranjayjain** [comment]
@zhuochun started work on this one will start a PR soon :+1:

**Comment by zhuochun** [comment]
@puranjayjain For this issue, I was thinking on providing the the auto closing tags. It is much like the standard package [bracket-matcher](https://github.com/atom/bracket-matcher) with more customization.

I was also hesitated because this feature itself could be just inside the bracket-matcher, the other packages could just hook into to register more pairs according to the file types.

**Comment by puranjayjain** [comment]
So shall we send a PR to bracket matcher itself?

**Comment by zhuochun** [comment]
Look like there is an issue on the similar topic https://github.com/atom/bracket-matcher/issues/182
