### ISSUE TITLE
Different list point based on indent level

### ISSUE THREAD

**Issue by zhuochun** [zhuochun/md-writer#154]
https://discuss.atom.io/t/modify-ordered-lists-and-bullet-pointers-in-markdown-writer-package/30018

In unordered list, is it possible to get different bullet markers when tab is pressed
For example, say, I have this list

```
+ first line
+ second line
```

In this, I go back to the first line and hit enter and tab, I get something like this

```
+ first line
     + 
+ second line
```

But I want something like this -

```
+ first line
     * 
+ second line
```

**Comment by ZelphirKaltstahl** [comment]
Why is `+` the top level and not `*` or any other for that matter? How do you decide which one would be top level and which the lower levels?
Is there an official standard for this? Why not have all the same symbols? How deep do you indent lists? Is that still readable or is bad readability the reason for wanting different characters to represent the bullets?

Imo this seems a bit too much of a random choice to pick an order like `+` , `*` and then something else. Maybe one could configure that somewhere, so that each user can have their own "ranking" of characters for bullets and indentation levels?

**Comment by zhuochun** [comment]
I agree that everyone has their preferences, that's why this plugins provided so much flexibility to customize. 

Please refer to the wiki for customizations.

**Comment by zhuochun** [comment]
Supported in 4d23def1fdca25cefb77dbabe254d75ab52c3ec1

Example usage by setting in config:

```
templateVariables:
  ulBullet: "-" # no indentation
  ulBullet1: "*" # indentation = 1
  ulBullet2: "+" # indentation = 2
```
