### ISSUE TITLE
Table formatting doesn't work if right below heading

### ISSUE THREAD

**Issue by calvn** [zhuochun/md-writer#172]
Table formatting doesn't work if it is right below a heading. I made sure to highlight only the table entry when doing the formatting. Having an extra space made it work, but took me some time to find out.

Example:
```markdown
## Heading
|                | title1  | title2 |
|----------------|-----------|---------------|
| item1   | Completed    |               |
| item2  | Not started |               |


## Heading

|       | title1      | title2 |
|-------|-------------|--------|
| item1 | Completed   |        |
| item2 | Not started |        |
```

**Comment by ZelphirKaltstahl** [comment]
I think this might be intentional. I think you're supposed to leave one empty line below headings anyway. There is at least indication of this on: <https://daringfireball.net/projects/markdown/syntax#header>. As you can see there is always a line in between. However, it does not explicitly state so.

**Comment by zhuochun** [comment]
As @ZelphirKaltstahl said, it is intentionally assumed that there is an empty line before the table.

**Comment by calvn** [comment]
I see, thanks for letting me know!
